// AUTO-GENERATED by cli/scripts/generate-skill-data.mjs. Do not edit by hand.
// Source: .agents/skills/*/SKILL.md frontmatter.
import type { SkillsRegistry } from "../types/index.js";

export const SKILLS: SkillsRegistry = {
  domain: [
    {
      name: "oma-architecture",
      desc: `Evaluate system boundaries and architectural tradeoffs. Use for architecture decisions, design reviews, and ADRs.`,
    },
    {
      name: "oma-backend",
      desc: `Implement server APIs, authentication, and application data access. Schema modeling and query tuning use oma-db.`,
    },
    {
      name: "oma-db",
      desc: `Design schemas and migrations, tune queries, or plan vector retrieval and database operations. Application API implementation uses oma-backend.`,
    },
    {
      name: "oma-frontend",
      desc: `Implement or modify web UI in React, Next.js, or Angular. Use for components, pages, styles, forms, and frontend state or data flows.`,
    },
    {
      name: "oma-mobile",
      desc: `Implement Flutter, React Native, or native Swift apps. Use for mobile screens, widgets, platform integrations, and application data flows.`,
    },
  ],
  design: [
    {
      name: "oma-design",
      desc: `Define or review a visual system, DESIGN.md, or redesign direction. Use for typography, layout, color, motion, and interaction design decisions.`,
    },
  ],
  coordination: [
    {
      name: "oma-brainstorm",
      desc: `Explore goals, constraints, and alternative approaches before choosing a design. Use when the user requests ideation or design exploration.`,
    },
    {
      name: "oma-coordination",
      desc: `Coordinate assigned specialist tasks and handoffs manually. Use when supervising a multi-agent project step by step.`,
    },
    {
      name: "oma-orchestration",
      desc: `Dispatch and supervise parallel specialist agents with durable task state. Use when automated multi-agent execution is requested.`,
    },
    {
      name: "oma-pm",
      desc: `Turn product requirements into scoped tasks with dependencies and acceptance criteria. Use for implementation planning and prioritization.`,
    },
    {
      name: "oma-qa",
      desc: `Review changes for correctness, security, accessibility, and performance. Use for scoped quality reviews or verification plans; bug fixes use oma-debug.`,
    },
  ],
  utility: [
    {
      name: "oma-academic-writing",
      desc: `Draft and revise academic prose against a rubric, evidence, and citation requirements. Use for essays, reports, literature reviews, or academic style audits.`,
    },
    {
      name: "oma-debug",
      desc: `Diagnose a reproducible failure, fix its cause, and verify the regression. Use for crashes, incorrect behavior, and failing tests.`,
    },
    {
      name: "oma-deepsec",
      desc: `Set up and run Deepsec vulnerability scans, triage, and CI gates. Use for Deepsec work or an explicitly requested agent-powered vulnerability scan.`,
    },
    {
      name: "oma-docs",
      desc: `Check documentation references, sync docs to code changes, and detect translation drift. Use for documentation maintenance in a repository.`,
    },
    {
      name: "oma-explanation",
      desc: `Create an offline HTML explanation of a code diff, PR, or branch. Use when an interactive code-change walkthrough is requested.`,
    },
    {
      name: "oma-hwp",
      desc: `Convert Hangul HWP, HWPX, or HWPML documents to Markdown with kordoc. Use for text, table, and image extraction from these formats.`,
    },
    {
      name: "oma-image",
      desc: `Generate raster images or reference-guided variations through the OMA image CLI. Use for image assets or explicit vendor comparisons; pixel editing uses an editor.`,
    },
    {
      name: "oma-market",
      desc: `Research customer pain points, trends, and competitors through the OMA market engine. Use for market discovery or voice-of-customer analysis.`,
    },
    {
      name: "oma-pdf",
      desc: `Extract PDF text, headings, tables, and images into Markdown using opendataloader-pdf. Use for PDF parsing, not PDF layout creation.`,
    },
    {
      name: "oma-recap",
      desc: `Summarize AI conversation histories for a specified date or period. Use for daily work recaps and cross-tool activity summaries.`,
    },
    {
      name: "oma-refactor",
      desc: `Restructure existing code while preserving observable behavior. Use for targeted technical debt or hotspot work with characterization tests.`,
    },
    {
      name: "oma-scholar",
      desc: `Search academic literature and generate, validate, or compare Knows paper sidecars. Use for claim/evidence analysis and literature synthesis.`,
    },
    {
      name: "oma-scm",
      desc: `Manage Git branches, merges, conflicts, commits, and release baselines. Use for repository history and change-management operations.`,
    },
    {
      name: "oma-search",
      desc: `Find external documentation, web sources, or remote code with citations. Local code navigation uses the configured code tools.`,
    },
    {
      name: "oma-skill-creation",
      desc: `Create or revise OMA skills and their references. Use for skill routing, execution contracts, conditional loading, and authoring validation.`,
    },
    {
      name: "oma-slide",
      desc: `Create, import, revise, or export presentation decks through the OMA slide CLI. Use for HTML slides and PDF, PNG, or PPTX deck delivery.`,
    },
    {
      name: "oma-translation",
      desc: `Translate or revise localized UI strings and prose while preserving meaning, terminology, placeholders, and structure.`,
    },
    {
      name: "oma-video",
      desc: `Create short, explainer, or recorded-demo videos through the OMA video CLI. Use for scripts, narration, assets, composition, and video delivery.`,
    },
    {
      name: "oma-voice",
      desc: `Generate speech or transcribe audio locally with Voicebox. Use for narration, voice assets, dictation, and meeting transcription.`,
    },
  ],
  infrastructure: [
    {
      name: "oma-dev-workflow",
      desc: `Configure development tasks, git hooks, CI/CD, or release automation. Use when creating or fixing a repository development workflow.`,
    },
    {
      name: "oma-observability",
      desc: `Design or troubleshoot telemetry, SLOs, and incident diagnostics. Route to the relevant signal, system boundary, or vendor guide.`,
    },
    {
      name: "oma-tf-infra",
      desc: `Create or review Terraform infrastructure and plans. Use for cloud resources, IAM, networking, state management, and infrastructure changes.`,
    },
  ],
};

export const PRESETS: Record<string, string[]> = {
  fullstack: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-backend",
    "oma-mobile",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-tf-infra",
    "oma-dev-workflow",
  ],
  "fullstack-web": [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  "fullstack-mobile": [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-mobile",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  frontend: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-design",
    "oma-frontend",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  backend: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-backend",
    "oma-db",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
    "oma-dev-workflow",
  ],
  mobile: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-mobile",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  devops: [
    "oma-architecture",
    "oma-brainstorm",
    "oma-tf-infra",
    "oma-dev-workflow",
    "oma-observability",
    "oma-pm",
    "oma-qa",
    "oma-debug",
    "oma-scm",
  ],
  research: [
    "oma-scholar",
    "oma-market",
    "oma-pdf",
    "oma-hwp",
    "oma-academic-writing",
    "oma-search",
    "oma-translation",
    "oma-scm",
  ],
  content: [
    "oma-design",
    "oma-image",
    "oma-voice",
    "oma-academic-writing",
    "oma-translation",
    "oma-scm",
  ],
  all: [
    ...SKILLS.domain,
    ...SKILLS.design,
    ...SKILLS.coordination,
    ...SKILLS.utility,
    ...SKILLS.infrastructure,
  ].map((s) => s.name),
};
