import fs from "node:fs";
import path from "node:path";

/**
 * OpenCode external-fallback dispatch wrapper (#583).
 *
 * OpenCode distinguishes primary agents from subagents. OMA role agents are
 * generated as `.opencode/agents/<id>.md` with `mode: subagent`, and they MUST
 * stay subagents so the in-session native `task` tool can dispatch them.
 *
 * The problem: `opencode run --agent <subagent>` refuses to run a `mode:
 * subagent` agent as the entry point. OpenCode prints
 *
 *   agent "<id>" is a subagent, not a primary agent. Falling back to default agent
 *
 * and runs the *default* agent instead. The process still exits 0, so the
 * external `oma agent:spawn` fallback silently runs the WRONG agent.
 *
 * Fix: for the external fallback only, generate a throwaway PRIMARY wrapper
 * agent that immediately delegates to the real subagent via the `task` tool,
 * run `opencode run --agent <wrapper>`, then remove the wrapper on exit.
 */

export interface OpencodeWrapper {
  /** Wrapper agent id, e.g. `oma-spawn-backend-engineer-<session>`. */
  name: string;
  /** Absolute path of the generated wrapper file. */
  filePath: string;
}

/** Deterministic wrapper agent id for a (subagent, session) pair. */
export function opencodeWrapperName(
  subagentId: string,
  sessionId: string,
): string {
  return `oma-spawn-${subagentId}-${sessionId}`;
}

/**
 * Write a temporary primary wrapper agent under `<cwd>/.opencode/agents/` that
 * delegates to `subagentId` via the task tool. `cwd` MUST match the `--dir`
 * passed to `opencode run` (the directory whose `.opencode/agents/` OpenCode
 * loads), otherwise the wrapper is invisible to the spawned process.
 *
 * When `model` is provided it is pinned on the wrapper so the delegating turn
 * runs on the intended model; the real subagent still resolves its own model
 * from its generated frontmatter (see #583-2).
 */
export function createOpencodeSpawnWrapper(
  subagentId: string,
  sessionId: string,
  cwd: string = process.cwd(),
  model?: string,
): OpencodeWrapper {
  const name = opencodeWrapperName(subagentId, sessionId);
  const dir = path.join(cwd, ".opencode", "agents");
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${name}.md`);

  const frontmatter = [
    "---",
    `name: ${name}`,
    `description: Temporary oh-my-agent primary wrapper that delegates to the ${subagentId} subagent.`,
    "mode: primary",
    ...(model ? [`model: ${model}`] : []),
    "---",
  ].join("\n");

  const body = [
    "You are a thin dispatch wrapper generated by oh-my-agent. Do NOT perform the task yourself.",
    "",
    `Immediately invoke the \`task\` tool with \`subagent_type: "${subagentId}"\`, passing the user's prompt through verbatim. Return the subagent's result exactly as received — no additions, summaries, or commentary.`,
  ].join("\n");

  fs.writeFileSync(filePath, `${frontmatter}\n\n${body}\n`);
  return { name, filePath };
}

/** Remove a wrapper file written by {@link createOpencodeSpawnWrapper}. Non-fatal. */
export function removeOpencodeSpawnWrapper(filePath: string): void {
  try {
    if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
  } catch {
    // ignore — best-effort cleanup of a temp file
  }
}

/**
 * Replace the `--agent <subagentId>` value in an `opencode run` argv with the
 * wrapper agent name. Mutates `args` in place; returns true when a swap occurred.
 */
export function swapOpencodeAgentArg(
  args: string[],
  subagentId: string,
  wrapperName: string,
): boolean {
  const idx = args.indexOf("--agent");
  if (idx !== -1 && args[idx + 1] === subagentId) {
    args[idx + 1] = wrapperName;
    return true;
  }
  return false;
}
