/**
 * Migration 031: Retire the project-local CLAUDE.md OMA block.
 *
 * Claude Code reads `AGENTS.md` natively from CLAUDE_AGENTS_MD_MIN_VERSION on,
 * so oma manages `AGENTS.md` only and `CLAUDE.md` is user-owned. For projects
 * whose `./CLAUDE.md` still carries a legacy `<!-- OMA:START … OMA:END -->`
 * block, this migration:
 *
 * 1. Strips the OMA block, keeping every other line the user wrote.
 * 2. Deletes the file only when the block was its sole content.
 * 3. Otherwise appends `@AGENTS.md`, because Claude Code reads CLAUDE.md
 *    alone when both files exist unless CLAUDE.md imports AGENTS.md.
 *
 * It runs only when the installed `claude` CLI is new enough; on older
 * versions the block is the only way Claude Code sees oma's instructions, so
 * it is left alone. AGENTS.md itself is regenerated by the reconcile (`link`)
 * step that follows migrations.
 */
import { existsSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import {
  appendAgentsMdImport,
  hasAgentsMdImport,
} from "../../platform/agents-md-import.js";
import {
  CLAUDE_AGENTS_MD_MIN_VERSION,
  claudeReadsAgentsMd,
  detectClaudeVersion,
} from "../../utils/claude-version.js";
import { atomicWriteFileSync } from "../../utils/safe-write.js";
import type { Migration } from "./index.js";
import { allowsVendor, type MigrationContext } from "./vendor-scope.js";

const OMA_START_PREFIX = "<!-- OMA:START";
const OMA_END = "<!-- OMA:END -->";

export function createClaudeMdAgentsMigration(
  detectVersion: () => string | null = detectClaudeVersion,
): Migration {
  return {
    name: "031-claude-md-agents",
    up(cwd: string, ctx?: MigrationContext): string[] {
      if (!allowsVendor(ctx, "claude")) return [];

      const claudeMd = join(cwd, "CLAUDE.md");
      if (!existsSync(claudeMd)) return [];

      let content: string;
      try {
        content = readFileSync(claudeMd, "utf-8");
      } catch {
        return [];
      }
      const startIdx = content.indexOf(OMA_START_PREFIX);
      const endIdx = content.indexOf(OMA_END);
      if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) return [];

      // Only probe the CLI once we know there is something to migrate.
      if (!claudeReadsAgentsMd(detectVersion())) return [];

      const before = content.slice(0, startIdx).trimEnd();
      const after = content.slice(endIdx + OMA_END.length).trim();
      const cleaned =
        before.length > 0 && after.length > 0
          ? `${before}\n\n${after}`
          : `${before}${after}`;

      try {
        if (cleaned.length === 0) {
          rmSync(claudeMd);
          return [
            `CLAUDE.md removed (OMA block was its only content; Claude Code >= ${CLAUDE_AGENTS_MD_MIN_VERSION} reads AGENTS.md)`,
          ];
        }
        const next = hasAgentsMdImport(cleaned)
          ? `${cleaned}\n`
          : appendAgentsMdImport(cleaned);
        atomicWriteFileSync(claudeMd, next);
        return [
          `CLAUDE.md: OMA block replaced with @AGENTS.md import (Claude Code >= ${CLAUDE_AGENTS_MD_MIN_VERSION} reads AGENTS.md)`,
        ];
      } catch {
        return [];
      }
    },
  };
}

export const migrateClaudeMdAgents: Migration = createClaudeMdAgentsMigration();
