import {
  ComponentError,
  type DiagramModel,
  findComponent,
  nearComponent,
  type RenderContext,
} from "./components/index.js";
import {
  type Draft,
  type DraftBlock,
  DraftError,
  type DraftPanel,
  parseDraft,
} from "./draft.js";
import { type LintWarning, lintDraft } from "./lint.js";
import { renderMarkdown } from "./markdown.js";
import { PAGE_SOURCE, PLANNER_SOURCE } from "./page-script.js";
import { type DraftLanguage, detectLanguage, escapeHtml } from "./text.js";
import { THEMES, type ThemeName, themeCss } from "./theme.js";

export const GENERATOR = "oma explain render";

export type StyleLevel = "off" | "warn" | "strict";
export type ColorMode = "auto" | "light" | "dark";

export interface RenderOptions {
  theme?: string;
  mode?: string;
  style?: string;
  lang?: string;
  /** Relative href of an archify sidecar to link from the page. */
  sidecarHref?: string;
  /** Shown in the footer; defaults to today. */
  date?: string;
}

export interface PanelDiagram {
  panelId: string;
  /** The panel carries the `archify` attribute. */
  preferred: boolean;
  title: string;
  model: DiagramModel;
}

export interface RenderResult {
  html: string;
  draft: Draft;
  lang: DraftLanguage;
  theme: ThemeName;
  style: StyleLevel;
  warnings: LintWarning[];
  /** Flow and sequence diagrams in the page, for the archify sidecar. */
  diagrams: PanelDiagram[];
}

interface Strings {
  right: string;
  wrong: string;
  theme: string;
  print: string;
  score: string;
  generated: string;
  interactive: string;
}

const STRINGS: Record<DraftLanguage, Strings> = {
  en: {
    right: "Correct.",
    wrong: "Not quite.",
    theme: "Light / Dark",
    print: "Print",
    score: "{correct} / {total} correct",
    generated: "Generated by",
    interactive: "Open the interactive diagram",
  },
  ko: {
    right: "정답입니다.",
    wrong: "오답입니다.",
    theme: "밝게 / 어둡게",
    print: "인쇄",
    score: "{total}문제 중 {correct}문제 정답",
    generated: "생성 도구",
    interactive: "인터랙티브 다이어그램 열기",
  },
  ja: {
    right: "正解です。",
    wrong: "不正解です。",
    theme: "ライト / ダーク",
    print: "印刷",
    score: "{total}問中 {correct}問正解",
    generated: "生成ツール",
    interactive: "インタラクティブ図を開く",
  },
  zh: {
    right: "回答正确。",
    wrong: "回答错误。",
    theme: "浅色 / 深色",
    print: "打印",
    score: "答对 {correct} / {total} 题",
    generated: "生成工具",
    interactive: "打开交互式图表",
  },
};

const LANGUAGES = new Set<string>(["en", "ko", "ja", "zh"]);
const DIFF_LANGS = new Set(["diff", "patch"]);

function pick<T extends string>(
  value: string | undefined,
  allowed: readonly T[],
  what: string,
): T | undefined {
  if (value === undefined || value === "") return undefined;
  const found = allowed.find((option) => option === value.toLowerCase());
  if (!found) {
    throw new DraftError(
      `${what} must be one of ${allowed.join(", ")}, not "${value}"`,
      1,
    );
  }
  return found;
}

function renderCode(block: Extract<DraftBlock, { type: "component" }>): string {
  const lines = block.text.split("\n");
  const body = DIFF_LANGS.has(block.name)
    ? lines
        .map((line) => {
          const escaped = escapeHtml(line) || " ";
          if (/^@@/.test(line))
            return `<span class="oe-code-hunk">${escaped}</span>`;
          if (/^\+(?!\+\+)/.test(line))
            return `<span class="oe-code-add">${escaped}</span>`;
          if (/^-(?!--)/.test(line))
            return `<span class="oe-code-del">${escaped}</span>`;
          return `${escaped}\n`;
        })
        .join("")
    : escapeHtml(block.text);
  const lang = block.name ? ` data-lang="${escapeHtml(block.name)}"` : "";
  return `<div class="oe-scroll"><pre${lang}><code>${body}</code></pre></div>`;
}

function renderBlock(
  block: DraftBlock,
  context: RenderContext,
  onModel: (model: DiagramModel) => void,
): string {
  if (block.type === "markdown") return renderMarkdown(block.text);
  const component = findComponent(block.name);
  if (!component) {
    const near = nearComponent(block.name);
    if (near) {
      throw new DraftError(
        `unknown component "${block.name}" — did you mean "${near.name}"?\n\n${near.syntax}`,
        block.line,
      );
    }
    // Any other fence is code: shown as written.
    return renderCode(block);
  }
  try {
    const result = component.render(block.text, block.args, context);
    if (result.model) onModel(result.model);
    return result.html;
  } catch (error) {
    if (error instanceof ComponentError) {
      throw new DraftError(
        `${error.message}\n\nSyntax of "${component.name}":\n${component.syntax}\n\nExample:\n${component.example}`,
        block.line + error.line,
      );
    }
    throw error;
  }
}

function renderPanel(
  panel: DraftPanel,
  context: RenderContext,
  cols: number,
  diagrams: PanelDiagram[],
  sidecar: { href: string; panelId: string; label: string } | undefined,
): string {
  const body = panel.blocks
    .map((block) =>
      renderBlock(block, context, (model) =>
        diagrams.push({
          panelId: panel.id,
          preferred: panel.archify,
          title: panel.title,
          model,
        }),
      ),
    )
    .join("\n");
  const span = panel.span ? Math.min(panel.span, cols) : undefined;
  const attrs = span
    ? ` data-span="${span}" style="grid-column:span ${span}"`
    : "";
  const head = panel.bare
    ? ""
    : `<header class="oe-panel-head"><span class="oe-panel-id">${escapeHtml(panel.id)}</span><h2>${escapeHtml(panel.title)}</h2>${panel.note ? `<span class="oe-panel-note">${escapeHtml(panel.note)}</span>` : ""}</header>`;
  const link =
    sidecar && sidecar.panelId === panel.id
      ? `\n<p><a class="oe-archify" href="${escapeHtml(sidecar.href)}">${escapeHtml(sidecar.label)} →</a></p>`
      : "";
  return `<section class="oe-panel" id="panel-${escapeHtml(panel.id.toLowerCase())}" aria-label="${escapeHtml(panel.title)}"${attrs}>${head}<div class="oe-panel-body">\n${body}${link}\n</div></section>`;
}

/** The diagram an archify sidecar is built from: a marked panel's, else the first. */
export function sidecarSource(
  diagrams: PanelDiagram[],
): PanelDiagram | undefined {
  return diagrams.find((diagram) => diagram.preferred) ?? diagrams[0];
}

/** JSON that is safe inside a <script> element. */
function scriptJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

const SOURCE_RE =
  /<script type="application\/json" id="oe-source">([\s\S]*?)<\/script>/;

/** The draft a rendered page was built from, or undefined for any other HTML. */
export function extractDraftSource(html: string): string | undefined {
  const match = SOURCE_RE.exec(html);
  if (!match) return undefined;
  try {
    const parsed = JSON.parse(match[1] as string) as { draft?: unknown };
    return typeof parsed.draft === "string" ? parsed.draft : undefined;
  } catch {
    return undefined;
  }
}

export function isRenderedPage(html: string): boolean {
  return html.includes(`<meta name="generator" content="${GENERATOR}">`);
}

/**
 * Draft → one self-contained HTML page. Throws DraftError, with the line in
 * the draft, when the draft or one of its components is malformed.
 */
export function renderDraft(
  source: string,
  options: RenderOptions = {},
): RenderResult {
  const draft = parseDraft(source);
  const { meta } = draft;
  const theme =
    pick(options.theme ?? meta.theme, THEMES, "theme") ?? "blueprint";
  const mode =
    pick<ColorMode>(
      options.mode ?? meta.mode,
      ["auto", "light", "dark"],
      "mode",
    ) ?? "auto";
  const style =
    pick<StyleLevel>(
      options.style ?? meta.style,
      ["off", "warn", "strict"],
      "style",
    ) ?? "warn";
  const requested = (options.lang ?? meta.lang)?.toLowerCase().slice(0, 2);
  const lang: DraftLanguage =
    requested && LANGUAGES.has(requested)
      ? (requested as DraftLanguage)
      : detectLanguage(source);
  const strings = STRINGS[lang];

  let counter = 0;
  const context: RenderContext = {
    lang,
    uid: (prefix) => `oe-${prefix}-${++counter}`,
  };
  const diagrams: PanelDiagram[] = [];
  const lead = draft.lead
    .map((block) => renderBlock(block, context, () => {}))
    .join("\n");

  // Panels render twice at most: the sidecar link needs to know which panel
  // owns the diagram, which is only known after a first pass.
  let panels = draft.panels.map((panel) =>
    renderPanel(panel, context, meta.cols, diagrams, undefined),
  );
  const origin = sidecarSource(diagrams);
  if (options.sidecarHref && origin) {
    counter = 0;
    const again: PanelDiagram[] = [];
    panels = draft.panels.map((panel) =>
      renderPanel(panel, context, meta.cols, again, {
        href: options.sidecarHref as string,
        panelId: origin.panelId,
        label: strings.interactive,
      }),
    );
  }

  const warnings = style === "off" ? [] : lintDraft(draft, lang);
  const metaLine = meta.extras
    .map(
      ([key, value]) =>
        `<span><b>${escapeHtml(key)}</b> ${escapeHtml(value)}</span>`,
    )
    .join("");
  const date = options.date ?? new Date().toISOString().slice(0, 10);
  const html = `<!doctype html>
<html lang="${lang}" data-oe-theme="${theme}"${mode === "auto" ? "" : ` data-theme="${mode}"`}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="generator" content="${GENERATOR}">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:">
<title>${escapeHtml(meta.title)}</title>
<style>
${themeCss(theme)}
</style>
</head>
<body>
<div class="oe-page">
<header class="oe-header">
<div>
<h1>${escapeHtml(meta.title)}</h1>
${meta.subtitle ? `<p class="oe-subtitle">${escapeHtml(meta.subtitle)}</p>` : ""}
${metaLine ? `<p class="oe-meta">${metaLine}</p>` : ""}
</div>
<div class="oe-tools">
<button type="button" data-oe="theme">${escapeHtml(strings.theme)}</button>
<button type="button" data-oe="print">${escapeHtml(strings.print)}</button>
</div>
</header>
<main>
${lead ? `<section class="oe-lead">\n${lead}\n</section>` : ""}
<div class="oe-grid" style="--cols:${meta.cols}">
${panels.join("\n")}
</div>
</main>
<footer class="oe-footer">
<span>${escapeHtml(strings.generated)} ${GENERATOR} · ${escapeHtml(date)}</span>
${options.sidecarHref && origin ? `<a href="${escapeHtml(options.sidecarHref)}">${escapeHtml(strings.interactive)} →</a>` : ""}
</footer>
</div>
<script type="application/json" id="oe-strings">${scriptJson({ score: strings.score, right: strings.right, wrong: strings.wrong })}</script>
<script type="application/json" id="oe-source">${scriptJson({ draft: source })}</script>
<script>
${PLANNER_SOURCE.trim()}
${PAGE_SOURCE.trim()}
</script>
</body>
</html>
`;
  return { html, draft, lang, theme, style, warnings, diagrams };
}

/**
 * Replace one panel of a draft. `replacement` is the new panel: its `## `
 * heading and body, or only a body, which keeps the current heading.
 */
export function patchDraft(
  source: string,
  panelId: string,
  replacement: string,
): string {
  const draft = parseDraft(source);
  const wanted = panelId.trim().toUpperCase();
  const index = draft.panels.findIndex((panel) => panel.id === wanted);
  const panel = draft.panels[index];
  if (!panel) {
    throw new DraftError(
      `no panel "${panelId}"; this page has ${draft.panels.map((p) => p.id).join(", ")}`,
      1,
    );
  }
  const lines = source.replace(/\r\n?/g, "\n").split("\n");
  const start = panel.line - 1;
  const end = draft.panels[index + 1]
    ? (draft.panels[index + 1] as DraftPanel).line - 1
    : lines.length;
  const body = replacement.replace(/\r\n?/g, "\n").trim();
  const fresh = /^##\s/.test(body) ? body : `${lines[start]}\n\n${body}`;
  const tail = lines.slice(end);
  return [
    ...lines.slice(0, start),
    ...fresh.split("\n"),
    ...(tail.length > 0 ? ["", ...tail] : [""]),
  ].join("\n");
}
