import {
  ComponentError,
  type DiagramModel,
  findComponent,
  nearComponent,
  type RenderContext,
} from "./components/index.js";
import {
  type Draft,
  type DraftBlock,
  DraftError,
  type DraftPanel,
  parseDraft,
  parsePanelHead,
} from "./draft.js";
import { type LintWarning, lintDraft } from "./lint.js";
import { renderMarkdown, tableColumns } from "./markdown.js";
import { PAGE_SOURCE, PLANNER_SOURCE } from "./page-script.js";
import { type DraftLanguage, detectLanguage, escapeHtml } from "./text.js";
import { THEMES, type ThemeName, themeCss } from "./theme.js";

export const GENERATOR = "oma explain render";

export const TEMPLATES = ["sheet", "doc"] as const;
export type TemplateName = (typeof TEMPLATES)[number];
export type StyleLevel = "off" | "warn" | "strict";
export type ColorMode = "auto" | "light" | "dark";

export interface RenderOptions {
  template?: string;
  theme?: string;
  mode?: string;
  style?: string;
  lang?: string;
  /** Relative href of an archify sidecar to link from the page. */
  sidecarHref?: string;
  /** Shown in the footer; defaults to today. */
  date?: string;
}

export interface PanelDiagram {
  panelId: string;
  /** The panel carries the `archify` attribute. */
  preferred: boolean;
  title: string;
  model: DiagramModel;
}

export interface RenderResult {
  html: string;
  draft: Draft;
  lang: DraftLanguage;
  template: TemplateName;
  theme: ThemeName;
  style: StyleLevel;
  warnings: LintWarning[];
  /** Flow and sequence diagrams in the page, for the archify sidecar. */
  diagrams: PanelDiagram[];
  /** How many times each component is used. */
  components: Record<string, number>;
}

interface Strings {
  right: string;
  wrong: string;
  theme: Record<ThemeName, string>;
  mode: Record<ColorMode, string>;
  copy: string;
  copied: string;
  print: string;
  score: string;
  contents: string;
  generated: string;
  interactive: string;
  flow: string;
  sequence: string;
  colon: string;
  separator: string;
}

const STRINGS: Record<DraftLanguage, Strings> = {
  en: {
    right: "Correct.",
    wrong: "Not quite.",
    theme: { blueprint: "Theme: Blueprint", card: "Theme: Cards" },
    mode: { auto: "Mode: Auto", light: "Mode: Light", dark: "Mode: Dark" },
    copy: "Copy draft",
    copied: "Copied ✓",
    print: "Print",
    score: "{correct} / {total} correct",
    contents: "Contents",
    generated: "Generated by",
    interactive: "Open the interactive diagram",
    flow: "Flowchart",
    sequence: "Sequence diagram",
    colon: ": ",
    separator: ", ",
  },
  ko: {
    right: "정답입니다.",
    wrong: "오답입니다.",
    theme: { blueprint: "테마: 도면", card: "테마: 카드" },
    mode: { auto: "명암: 자동", light: "명암: 밝게", dark: "명암: 어둡게" },
    copy: "초안 복사",
    copied: "복사했습니다 ✓",
    print: "인쇄",
    score: "{total}문제 중 {correct}문제 정답",
    contents: "목차",
    generated: "생성 도구",
    interactive: "인터랙티브 다이어그램 열기",
    flow: "흐름도",
    sequence: "시퀀스 다이어그램",
    colon: ": ",
    separator: ", ",
  },
  ja: {
    right: "正解です。",
    wrong: "不正解です。",
    theme: { blueprint: "テーマ：図面", card: "テーマ：カード" },
    mode: { auto: "表示：自動", light: "表示：ライト", dark: "表示：ダーク" },
    copy: "原稿をコピー",
    copied: "コピーしました ✓",
    print: "印刷",
    score: "{total}問中 {correct}問正解",
    contents: "目次",
    generated: "生成ツール",
    interactive: "インタラクティブ図を開く",
    flow: "フローチャート",
    sequence: "シーケンス図",
    colon: "：",
    separator: "、",
  },
  zh: {
    right: "回答正确。",
    wrong: "回答错误。",
    theme: { blueprint: "主题：图纸", card: "主题：卡片" },
    mode: { auto: "明暗：跟随系统", light: "明暗：亮", dark: "明暗：暗" },
    copy: "复制源稿",
    copied: "已复制 ✓",
    print: "打印",
    score: "答对 {correct} / {total} 题",
    contents: "目录",
    generated: "生成工具",
    interactive: "打开交互式图表",
    flow: "流程图",
    sequence: "时序图",
    colon: "：",
    separator: "、",
  },
};

const LANGUAGES = new Set<string>(["en", "ko", "ja", "zh"]);
const DIFF_LANGS = new Set(["diff", "patch"]);

function pick<T extends string>(
  value: string | undefined,
  allowed: readonly T[],
  what: string,
): T | undefined {
  if (value === undefined || value === "") return undefined;
  const found = allowed.find((option) => option === value.toLowerCase());
  if (!found) {
    throw new DraftError(
      `${what} must be one of ${allowed.join(", ")}, not "${value}"`,
      1,
    );
  }
  return found;
}

function renderCode(block: Extract<DraftBlock, { type: "component" }>): string {
  const lines = block.text.split("\n");
  const body = DIFF_LANGS.has(block.name)
    ? lines
        .map((line) => {
          const escaped = escapeHtml(line) || " ";
          if (/^@@/.test(line)) {
            return `<span class="oe-code-hunk">${escaped}</span>`;
          }
          if (/^\+(?!\+\+)/.test(line)) {
            return `<span class="oe-code-add">${escaped}</span>`;
          }
          if (/^-(?!--)/.test(line)) {
            return `<span class="oe-code-del">${escaped}</span>`;
          }
          return `${escaped}\n`;
        })
        .join("")
    : escapeHtml(block.text);
  const lang = block.name ? ` data-lang="${escapeHtml(block.name)}"` : "";
  return `<div class="oe-scroll"><pre${lang}><code>${body}</code></pre></div>`;
}

interface Collector {
  context: RenderContext;
  components: Record<string, number>;
}

function renderBlock(
  block: DraftBlock,
  collector: Collector,
  onModel: (model: DiagramModel) => void,
): string {
  if (block.type === "markdown") return renderMarkdown(block.text);
  const component = findComponent(block.name);
  if (!component) {
    const near = nearComponent(block.name);
    if (near) {
      throw new DraftError(
        `unknown component "${block.name}" — did you mean "${near.name}"?\n\n${near.syntax}`,
        block.line,
      );
    }
    // Any other fence is code: shown as written.
    return renderCode(block);
  }
  collector.components[block.name] =
    (collector.components[block.name] ?? 0) + 1;
  try {
    const result = component.render(block.text, block.args, collector.context);
    if (result.model) onModel(result.model);
    return result.html;
  } catch (error) {
    if (error instanceof ComponentError) {
      throw new DraftError(
        `${error.message}\n\nSyntax of "${component.name}":\n${component.syntax}\n\nExample:\n${component.example}`,
        block.line + error.line,
      );
    }
    throw error;
  }
}

// A wide table or a wide diagram does not fit one grid column: too many
// columns squeeze a cell to a word per line, and a diagram shrinks until its
// text is unreadable. These panels get a wider span without the author asking.
const WIDE_TABLE_COLUMNS = 4;
const TABLE_COLUMNS_PER_SPAN = 2;
const DIAGRAM_WIDTH_PER_SPAN = 560;

/** Grid columns the panel's content needs, when the author set no span. */
export function contentSpan(panel: DraftPanel, html: string): number {
  const columns = Math.max(
    0,
    ...panel.blocks.map((block) =>
      block.type === "markdown" ? tableColumns(block.text) : 0,
    ),
  );
  const widest = Math.max(
    0,
    ...[...html.matchAll(/<svg\b[^>]*?\sdata-natural="(\d+)"/g)].map((match) =>
      Number(match[1]),
    ),
  );
  return Math.max(
    1,
    columns >= WIDE_TABLE_COLUMNS
      ? Math.ceil(columns / TABLE_COLUMNS_PER_SPAN)
      : 1,
    Math.ceil(widest / DIAGRAM_WIDTH_PER_SPAN),
  );
}

/**
 * Spans for the plain grid, in reading order: when the columns left in a row
 * cannot take the next panel, the current one widens to fill the row, so the
 * grid has no holes. With a panel that spans rows the author's layout stands.
 */
export function fillRows(
  spans: number[],
  cols: number,
  rowSpans: boolean,
): number[] {
  const clamped = spans.map((span) => Math.max(1, Math.min(span, cols)));
  if (rowSpans) return clamped;
  let used = 0;
  return clamped.map((span, index) => {
    if (used + span > cols) used = 0;
    used += span;
    const next = clamped[index + 1];
    const fill = next === undefined || used + next > cols ? cols - used : 0;
    used = fill > 0 || used === cols ? 0 : used;
    return span + fill;
  });
}

interface RenderedPanel {
  panel: DraftPanel;
  body: string;
}

function panelHtml(
  { panel, body }: RenderedPanel,
  layout: { span: number; grid: boolean; cols: number },
  link: string,
): string {
  const styles: string[] = [];
  if (layout.grid && layout.span > 1) {
    styles.push(`grid-column:span ${layout.span}`);
  }
  if (layout.grid && panel.rows && panel.rows > 1) {
    styles.push(`grid-row:span ${panel.rows}`);
  }
  // data-span carries only what the author wrote; the row planner treats it
  // as a hint and sizes every other panel from its content.
  const hint =
    layout.grid && panel.span
      ? ` data-span="${Math.min(panel.span, layout.cols)}"`
      : "";
  const style = styles.length > 0 ? ` style="${styles.join(";")}"` : "";
  const head = panel.bare
    ? ""
    : `<header class="oe-panel-head"><span class="oe-panel-id">${escapeHtml(panel.id)}</span><h2>${escapeHtml(panel.title)}</h2>${panel.note ? `<span class="oe-panel-note">${escapeHtml(panel.note)}</span>` : ""}</header>`;
  return `<section class="oe-panel" id="panel-${escapeHtml(panel.id.toLowerCase())}" aria-label="${escapeHtml(panel.title)}"${hint}${style}>${head}<div class="oe-panel-body">\n${body}${link}\n</div></section>`;
}

/** The diagram an archify sidecar is built from: a marked panel's, else the first. */
export function sidecarSource(
  diagrams: PanelDiagram[],
): PanelDiagram | undefined {
  return diagrams.find((diagram) => diagram.preferred) ?? diagrams[0];
}

/** JSON that is safe inside a <script> element. */
function scriptJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

const SOURCE_RE =
  /<script type="application\/json" id="oe-source">([\s\S]*?)<\/script>/;

/** The draft a rendered page was built from, or undefined for any other HTML. */
export function extractDraftSource(html: string): string | undefined {
  const match = SOURCE_RE.exec(html);
  if (!match) return undefined;
  try {
    const parsed = JSON.parse(match[1] as string) as { draft?: unknown };
    return typeof parsed.draft === "string" ? parsed.draft : undefined;
  } catch {
    return undefined;
  }
}

/** Settings a page was rendered with, read back from its root element. */
export function readPageSettings(html: string): {
  template?: string;
  theme?: string;
  mode?: string;
  style?: string;
  sidecarHref?: string;
} {
  const root = /<html\b[^>]*>/.exec(html)?.[0] ?? "";
  const attr = (name: string) =>
    new RegExp(`\\s${name}="([^"]+)"`).exec(root)?.[1];
  return {
    template: attr("data-oe-template"),
    theme: attr("data-oe-theme"),
    mode: attr("data-theme"),
    style: attr("data-oe-style"),
    sidecarHref: /class="oe-archify" href="([^"]+)"/.exec(html)?.[1],
  };
}

export function isRenderedPage(html: string): boolean {
  return html.includes(`<meta name="generator" content="${GENERATOR}">`);
}

const RULER_NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8];
const RULER_LETTERS = ["A", "B", "C", "D"];

function ruler(side: string, labels: Array<string | number>): string {
  return `<div class="oe-ruler oe-ruler-${side}" aria-hidden="true">${labels.map((label) => `<span>${label}</span>`).join("")}</div>`;
}

/**
 * Draft → one self-contained HTML page. Throws DraftError, with the line in
 * the draft, when the draft or one of its components is malformed.
 */
export function renderDraft(
  source: string,
  options: RenderOptions = {},
): RenderResult {
  const draft = parseDraft(source);
  const { meta } = draft;
  const template =
    pick(options.template ?? meta.template, TEMPLATES, "template") ?? "sheet";
  const theme =
    pick(options.theme ?? meta.theme, THEMES, "theme") ?? "blueprint";
  const mode =
    pick<ColorMode>(
      options.mode ?? meta.mode,
      ["auto", "light", "dark"],
      "mode",
    ) ?? "auto";
  const style =
    pick<StyleLevel>(
      options.style ?? meta.style,
      ["off", "warn", "strict"],
      "style",
    ) ?? "warn";
  const requested = (options.lang ?? meta.lang)?.toLowerCase().slice(0, 2);
  const lang: DraftLanguage =
    requested && LANGUAGES.has(requested)
      ? (requested as DraftLanguage)
      : detectLanguage(source);
  const strings = STRINGS[lang];

  let counter = 0;
  const collector: Collector = {
    context: {
      lang,
      uid: (prefix) => `oe-${prefix}-${++counter}`,
      labels: {
        flow: strings.flow,
        sequence: strings.sequence,
        colon: strings.colon,
        separator: strings.separator,
      },
    },
    components: {},
  };
  const diagrams: PanelDiagram[] = [];
  const lead = draft.lead
    .map((block) => renderBlock(block, collector, () => {}))
    .join("\n");
  const rendered: RenderedPanel[] = draft.panels.map((panel) => ({
    panel,
    body: panel.blocks
      .map((block) =>
        renderBlock(block, collector, (model) =>
          diagrams.push({
            panelId: panel.id,
            preferred: panel.archify,
            title: panel.title,
            model,
          }),
        ),
      )
      .join("\n"),
  }));

  const origin = sidecarSource(diagrams);
  const linked = options.sidecarHref && origin ? options.sidecarHref : "";
  const linkFor = (panel: DraftPanel) =>
    linked && origin?.panelId === panel.id
      ? `\n<p><a class="oe-archify" href="${escapeHtml(linked)}">${escapeHtml(strings.interactive)} →</a></p>`
      : "";

  let main: string;
  if (template === "doc") {
    const toc =
      rendered.length >= 3
        ? `<nav class="oe-toc" aria-label="${escapeHtml(strings.contents)}">${rendered.map(({ panel }) => `<a href="#panel-${escapeHtml(panel.id.toLowerCase())}">${escapeHtml(panel.id)} · ${escapeHtml(panel.title)}</a>`).join("")}</nav>`
        : "";
    main = `<div class="oe-doc${toc ? "" : " oe-doc-plain"}">
${toc}<div class="oe-doc-body">
${rendered.map((entry) => panelHtml(entry, { span: 1, grid: false, cols: 1 }, linkFor(entry.panel))).join("\n")}
</div>
</div>`;
  } else {
    const spans = fillRows(
      rendered.map(({ panel, body }) => panel.span ?? contentSpan(panel, body)),
      meta.cols,
      rendered.some(({ panel }) => (panel.rows ?? 1) > 1),
    );
    main = `<div class="oe-frame">
${ruler("top", RULER_NUMBERS)}${ruler("bottom", RULER_NUMBERS)}${ruler("left", RULER_LETTERS)}${ruler("right", RULER_LETTERS)}
<div class="oe-grid" style="--cols:${meta.cols}">
${rendered.map((entry, index) => panelHtml(entry, { span: spans[index] as number, grid: true, cols: meta.cols }, linkFor(entry.panel))).join("\n")}
</div>
</div>`;
  }

  const warnings = style === "off" ? [] : lintDraft(draft, lang);
  const metaLine = meta.extras
    .map(
      ([key, value]) =>
        `<span><b>${escapeHtml(key)}</b> ${escapeHtml(value)}</span>`,
    )
    .join("");
  const date = options.date ?? new Date().toISOString().slice(0, 10);
  const page = {
    themes: THEMES,
    theme: strings.theme,
    mode: strings.mode,
    copied: strings.copied,
    score: strings.score,
    right: strings.right,
    wrong: strings.wrong,
  };
  const html = `<!doctype html>
<html lang="${lang === "zh" ? "zh-CN" : lang}" data-oe-template="${template}" data-oe-theme="${theme}" data-oe-style="${style}"${mode === "auto" ? "" : ` data-theme="${mode}"`}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="generator" content="${GENERATOR}">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:">
<title>${escapeHtml(meta.title)}</title>
<style>
${themeCss()}
</style>
</head>
<body>
<div class="oe-page">
<header class="oe-header">
<div>
<h1>${escapeHtml(meta.title)}</h1>
${meta.subtitle ? `<p class="oe-subtitle">${escapeHtml(meta.subtitle)}</p>` : ""}
${metaLine ? `<p class="oe-meta">${metaLine}</p>` : ""}
</div>
<div class="oe-tools">
<button type="button" data-oe="theme">${escapeHtml(strings.theme[theme])}</button>
<button type="button" data-oe="mode">${escapeHtml(strings.mode[mode])}</button>
<button type="button" data-oe="copy">${escapeHtml(strings.copy)}</button>
<button type="button" data-oe="print">${escapeHtml(strings.print)}</button>
</div>
</header>
<main>
${lead ? `<section class="oe-lead">\n${lead}\n</section>` : ""}
${main}
</main>
<footer class="oe-footer">
<span>${escapeHtml(strings.generated)} ${GENERATOR} · ${escapeHtml(date)}</span>
${linked ? `<a href="${escapeHtml(linked)}">${escapeHtml(strings.interactive)} →</a>` : ""}
</footer>
</div>
<script type="application/json" id="oe-strings">${scriptJson(page)}</script>
<script type="application/json" id="oe-source">${scriptJson({ draft: source })}</script>
<script>
${PLANNER_SOURCE.trim()}
${PAGE_SOURCE.trim()}
</script>
</body>
</html>
`;
  return {
    html,
    draft,
    lang,
    template,
    theme,
    style,
    warnings,
    diagrams,
    components: collector.components,
  };
}

/** `## B Title {span=2}`, `B Title`, `B`, or `Title` → what the author meant. */
function panelQuery(query: string): string {
  const text = query.trim().replace(/^##\s*/, "");
  return text.replace(/\s*\{[^{}]*\}\s*$/, "").trim();
}

/** The panel a query names: by id, by title, or by "id title". */
export function findPanel(draft: Draft, query: string): DraftPanel {
  const wanted = panelQuery(query);
  if (!wanted) throw new DraftError("--panel needs a panel id or title", 1);
  const exact = draft.panels.filter(
    (panel) =>
      panel.title === wanted ||
      panel.id === wanted ||
      `${panel.id} ${panel.title}` === wanted,
  );
  const matches =
    exact.length > 0
      ? exact
      : draft.panels.filter(
          (panel) =>
            panel.id.toLowerCase() === wanted.toLowerCase() ||
            panel.title.toLowerCase() === wanted.toLowerCase(),
        );
  if (matches.length === 0) {
    throw new DraftError(
      `no panel "${query}"; this page has ${draft.panels.map((panel) => `${panel.id} ${panel.title}`).join(", ")}`,
      1,
    );
  }
  if (matches.length > 1) {
    throw new DraftError(
      `"${query}" matches more than one panel; use the panel letter`,
      1,
    );
  }
  return matches[0] as DraftPanel;
}

/**
 * Replace one panel of a draft. `replacement` is the new panel: its `## `
 * heading and body, or only a body, which keeps the current heading.
 */
export function patchDraft(
  source: string,
  query: string,
  replacement: string,
): string {
  const draft = parseDraft(source);
  const panel = findPanel(draft, query);
  const index = draft.panels.indexOf(panel);
  const lines = source.replace(/\r\n?/g, "\n").split("\n");
  const start = panel.line - 1;
  const next = draft.panels[index + 1];
  const end = next ? next.line - 1 : lines.length;
  const body = replacement.replace(/\r\n?/g, "\n").trim();
  if (!body) throw new DraftError("the new panel is empty", 1);
  const headed = /^##\s/.test(body);
  const headings = body.split("\n").filter((line) => /^##\s/.test(line)).length;
  if (headings > 1) {
    throw new DraftError("the new panel must hold exactly one ## heading", 1);
  }
  if (headed) {
    // A new heading without a letter keeps the panel's place in the order.
    const head = parsePanelHead((body.split("\n")[0] as string).slice(3), 1);
    if (
      head.id &&
      head.id !== panel.id &&
      draft.panels.some((p) => p.id === head.id)
    ) {
      throw new DraftError(
        `the new heading uses the id "${head.id}", which another panel has`,
        1,
      );
    }
  }
  const fresh = headed ? body : `${lines[start]}\n\n${body}`;
  const tail = lines.slice(end);
  return [
    ...lines.slice(0, start),
    ...fresh.split("\n"),
    ...(tail.length > 0 ? ["", ...tail] : [""]),
  ].join("\n");
}
