/**
 * Doctor check — oma-hook.sh binary resolvability (design 019 §T1-d).
 *
 * For each hook-model vendor, if `<projectDir>/<hookDir>/oma-hook.sh` is
 * present the check verifies that the oma binary is resolvable the same
 * way the wrapper does at runtime (either source is enough):
 *
 *   1. The path recorded in the wrapper at install time, `${HOME}` expanded
 *      (exists + executable)
 *   2. `command -v oma` on the current PATH (PATH lookup via executableSearchPaths)
 *
 * Possible outcomes per vendor:
 *   - "skip"    — wrapper not installed (vendor not set up); check is silent / N/A.
 *   - "pass"    — oma is resolvable; hook will dispatch correctly.
 *   - "warning" — oma is NOT resolvable; reports advisory with remediation.
 *
 * Fail-open: this is a WARNING, never a hard error — the wrapper itself
 * exits 0 when oma is missing so the agent is never blocked.
 */

import {
  accessSync,
  existsSync,
  constants as fsConstants,
  readFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { VARIANT_ROUTES } from "../hook/dispatch.js";

// ---------------------------------------------------------------------------
// Vendor → hookDir table — derived from the embedded variant route table so
// doctor coverage can never drift from what `oma hook` actually dispatches.
// antigravity is excluded: its `.agents/hooks.json` runs handlers directly via
// bun from `.agents/hooks/core` — no oma-hook.sh wrapper exists for it.
// ---------------------------------------------------------------------------

const PROJECT_HOOK_DIRS: Array<{ vendor: string; hookDir: string }> =
  Object.values(VARIANT_ROUTES)
    .filter((v) => v.vendor !== "antigravity")
    .map(({ vendor, hookDir }) => ({ vendor, hookDir }));

/** Filename written by generateOmaHookWrapper / installHooksFromVariant. */
const OMA_HOOK_WRAPPER_FILENAME = "oma-hook.sh";

// ---------------------------------------------------------------------------
// Binary resolution helpers (mirrors the wrapper's own resolution strategy)
// ---------------------------------------------------------------------------

function canExecute(filePath: string): boolean {
  try {
    accessSync(filePath, fsConstants.X_OK);
    return true;
  } catch {
    return false;
  }
}

function executableSearchPaths(env: NodeJS.ProcessEnv): string[] {
  const home = homedir();
  return [
    ...(env.PATH ?? "").split(":"),
    join(home, ".bun", "bin"),
    join(home, ".local", "bin"),
    "/opt/homebrew/bin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ].filter((p, i, arr) => p && arr.indexOf(p) === i);
}

/** True when `oma` is found on the current PATH. */
function omaOnPath(env: NodeJS.ProcessEnv): boolean {
  for (const dir of executableSearchPaths(env)) {
    const candidate = join(dir, "oma");
    if (existsSync(candidate) && canExecute(candidate)) return true;
  }
  return false;
}

/**
 * Extract the recorded absolute oma path from an oma-hook.sh wrapper.
 *
 * The wrapper generated by `generateOmaHookWrapper` contains:
 *   elif [ -x "<recordedPath>" ]; then
 *
 * We match that line to recover the path written at install time.
 * Returns null if the wrapper doesn't contain the expected pattern
 * (e.g. it's an older wrapper or has been modified).
 *
 * A path under the installing user's home is recorded as a literal `${HOME}`
 * prefix (machine-independent — see generateOmaHookWrapper); expand it here the
 * way the shell would before testing the file.
 */
function extractRecordedPath(wrapperContent: string): string | null {
  const match = wrapperContent.match(/\[ -x "([^"]+)" \]/);
  const recorded = match?.[1];
  if (!recorded) return null;
  return recorded.replace(/^\$\{HOME\}(?=\/|$)/, homedir());
}

/** True when the recorded install-time path still exists and is executable. */
function recordedPathResolvable(wrapperPath: string): boolean {
  let content: string;
  try {
    content = readFileSync(wrapperPath, "utf-8");
  } catch {
    return false;
  }
  const recorded = extractRecordedPath(content);
  if (!recorded) return false;
  return existsSync(recorded) && canExecute(recorded);
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type HookWrapperCheckStatus = "skip" | "pass" | "warning";

export interface HookWrapperCheck {
  vendor: string;
  wrapperPath: string;
  status: HookWrapperCheckStatus;
  /** Human-readable remediation hint, present when status === "warning". */
  remediation?: string;
}

// ---------------------------------------------------------------------------
// Per-vendor check
// ---------------------------------------------------------------------------

function checkWrapper(
  vendor: string,
  wrapperPath: string,
  env: NodeJS.ProcessEnv,
): HookWrapperCheck {
  if (!existsSync(wrapperPath)) {
    return { vendor, wrapperPath, status: "skip" };
  }

  const resolvable = omaOnPath(env) || recordedPathResolvable(wrapperPath);
  if (resolvable) {
    return { vendor, wrapperPath, status: "pass" };
  }

  return {
    vendor,
    wrapperPath,
    status: "warning",
    remediation: "Run 'oma link' to regenerate the hook wrapper",
  };
}

// ---------------------------------------------------------------------------
// Public collector
// ---------------------------------------------------------------------------

/**
 * Collect oma-hook.sh resolvability checks for all hook-model vendors.
 *
 * @param projectDir - The project root (process.cwd() in normal usage).
 * @param env - Process environment; defaults to `process.env`.
 *   Override in tests to control PATH and env vars.
 */
export function collectHookWrapperChecks(
  projectDir: string,
  env: NodeJS.ProcessEnv = process.env,
): HookWrapperCheck[] {
  const checks: HookWrapperCheck[] = [];

  for (const { vendor, hookDir } of PROJECT_HOOK_DIRS) {
    const wrapperPath = join(
      projectDir,
      ...hookDir.split("/"),
      OMA_HOOK_WRAPPER_FILENAME,
    );
    checks.push(checkWrapper(vendor, wrapperPath, env));
  }

  return checks;
}
