import {
  STANDALONE_HOOK_SCRIPTS,
  type StandaloneHookVendor,
} from "../../constants/standalone-hooks.js";

/** Generated Bun entry; all handler logic stays in the installed CLI. */
export function standaloneHookSources(
  vendor: StandaloneHookVendor,
  omaHome?: string,
): ReadonlyMap<string, string> {
  return new Map(
    Object.keys(STANDALONE_HOOK_SCRIPTS).map((script) => [
      script,
      `// Generated by OMA. Handler implementation lives in the CLI.
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";

if (import.meta.main) {
  try {
    const result = spawnSync(process.env.OMA_BIN || "oma", [
      "hook", "script", "--vendor", ${JSON.stringify(vendor)},
      "--script", ${JSON.stringify(script)},
    ], {
      input: readFileSync(0),
      cwd: process.cwd(),
      env: ${omaHome ? `{ ...process.env, OMA_HOME: ${JSON.stringify(omaHome)} }` : "process.env"},
      encoding: "utf-8",
      timeout: ${script === "persistent-mode.ts" ? 35_000 : 7_000},
      maxBuffer: 4 * 1024 * 1024,
    });
    if (result.error) throw result.error;
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
  } catch (error) {
    process.stderr.write("[oma hook] standalone dispatch unavailable: " + String(error) + "\\n");
  }
}
`,
    ]),
  );
}
