import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { loadVideoConfig } from "./config.js";
import { VideoOrchestrator } from "./orchestrator.js";
import { defaultVideoRegistry } from "./registry.js";

describe("demo source dispatch", () => {
  let tmp: string;
  const originalMock = process.env.OMA_VIDEO_MOCK;

  beforeEach(() => {
    tmp = mkdtempSync(path.join(os.tmpdir(), "oma-video-web-"));
    process.env.OMA_VIDEO_MOCK = "1";
  });
  afterEach(() => {
    rmSync(tmp, { recursive: true, force: true });
    if (originalMock === undefined) delete process.env.OMA_VIDEO_MOCK;
    else process.env.OMA_VIDEO_MOCK = originalMock;
  });

  async function run(opts: Record<string, unknown>) {
    const config = await loadVideoConfig(tmp);
    const orchestrator = new VideoOrchestrator(
      config,
      defaultVideoRegistry(config, { cwd: tmp }),
    );
    return orchestrator.generate({
      brief: "walk through the flow",
      opts: { dryRun: true, mode: "demo", ...opts },
      cwd: tmp,
    });
  }

  it("rejects --source web without --url (SchemaValidationError → exit 4)", async () => {
    const result = await run({ source: "web" });
    expect(result.exitCode).toBe(4);
    expect(result.error).toContain("--url");
  });

  it("stops with guided capture-required when web capture is unavailable", async () => {
    const result = await run({ source: "web", url: "https://example.com" });
    expect(result.exitCode).toBe(3);
    expect(result.manifest?.providers.capture).toBe("cap");
    const joined = result.warnings.join("\n");
    expect(joined).toContain("Capture is performed by a human");
    // The URL is masked (no raw query); the manifest records the masked URL.
    expect(result.manifest?.captureUrlMasked).toContain("https://example.com");
  });

  it("masks query tokens in the manifest captureUrlMasked", async () => {
    const result = await run({
      source: "web",
      url: "https://example.com/app?token=supersecretvalue",
    });
    expect(result.exitCode).toBe(3);
    const masked = result.manifest?.captureUrlMasked ?? "";
    expect(masked).not.toContain("supersecretvalue");
    expect(masked).toContain("<redacted>");
  });

  it("defaults to the file source and stops with capture-required", async () => {
    const result = await run({});
    expect(result.exitCode).toBe(3);
    expect(result.manifest?.providers.capture).toBe("cap");
    expect(result.warnings.join("\n")).toContain(
      "Capture is performed by a human",
    );
  });
});

describe("ffprobe-validate helper", () => {
  function ffprobeStreamType(file: string): string | null {
    try {
      const out = execFileSync(
        "ffprobe",
        [
          "-v",
          "error",
          "-select_streams",
          "v:0",
          "-show_entries",
          "stream=codec_type",
          "-of",
          "default=noprint_wrappers=1:nokey=1",
          file,
        ],
        { encoding: "utf8" },
      );
      return out.trim() || null;
    } catch {
      return null;
    }
  }

  it("returns null for a non-video placeholder file", () => {
    const tmp = mkdtempSync(path.join(os.tmpdir(), "oma-ffprobe-"));
    const file = path.join(tmp, "placeholder.mp4");
    writeFileSync(file, "oma-video placeholder render\n", "utf8");
    try {
      expect(ffprobeStreamType(file)).toBeNull();
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });

  it("reports a video stream for a real mp4 generated by ffmpeg", () => {
    const tmp = mkdtempSync(path.join(os.tmpdir(), "oma-ffprobe-"));
    const file = path.join(tmp, "real.mp4");
    try {
      // Generate a tiny real mp4 with ffmpeg; skip gracefully if absent.
      try {
        execFileSync(
          "ffmpeg",
          [
            "-y",
            "-f",
            "lavfi",
            "-i",
            "color=c=black:s=320x240:d=1",
            "-pix_fmt",
            "yuv420p",
            file,
          ],
          { stdio: "ignore" },
        );
      } catch {
        return; // ffmpeg not available — nothing to assert
      }
      expect(ffprobeStreamType(file)).toBe("video");
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});
