import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { parseFrontmatter } from "../../utils/frontmatter.js";
import { readRules } from "../rules.js";
import { discoverSkillDirs, SKILLS_DIR } from "./agent-skills.js";
import type { AgentsMdEmitReport } from "./types.js";

/** Existing root AGENTS.md — never overwritten by emit (see platform/rules.ts, which owns it). */
export const EXISTING_AGENTS_MD_PATH = "AGENTS.md";

const WORKFLOWS_DIR = ".agents/workflows";

interface IndexEntry {
  name: string;
  file: string;
  description: string;
}

/**
 * Collapse a frontmatter description into a single Markdown table cell:
 * YAML folded (`>`) scalars carry embedded/trailing newlines that would
 * otherwise corrupt the table, and a literal `|` would terminate the cell
 * early.
 */
function toTableCell(description: string): string {
  return description.replace(/\s+/g, " ").trim().replace(/\|/g, "\\|");
}

function discoverSkillIndex(repoRoot: string): IndexEntry[] {
  return discoverSkillDirs(repoRoot).map((dirName) => {
    const skillMdPath = join(repoRoot, SKILLS_DIR, dirName, "SKILL.md");
    const content = existsSync(skillMdPath)
      ? readFileSync(skillMdPath, "utf-8")
      : "";
    const { frontmatter } = parseFrontmatter(content);
    return {
      name: dirName,
      file: `${SKILLS_DIR}/${dirName}/SKILL.md`,
      description:
        typeof frontmatter.description === "string"
          ? frontmatter.description
          : "",
    };
  });
}

/** Top-level `.agents/workflows/*.md` files (skips subdirectories like `ralph/`, `ultrawork/`). */
function discoverWorkflowIndex(repoRoot: string): IndexEntry[] {
  const dir = join(repoRoot, WORKFLOWS_DIR);
  if (!existsSync(dir)) return [];

  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => {
      const filePath = join(dir, entry.name);
      const content = readFileSync(filePath, "utf-8");
      const { frontmatter } = parseFrontmatter(content);
      const name = entry.name.replace(/\.md$/, "");
      return {
        name: typeof frontmatter.name === "string" ? frontmatter.name : name,
        file: `${WORKFLOWS_DIR}/${entry.name}`,
        description:
          typeof frontmatter.description === "string"
            ? frontmatter.description
            : "",
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Build a compact, spec-friendly AGENTS.md (https://agents.md convention):
 * project rules pointers, skill index, and workflow index, all generated
 * directly from the `.agents/` SSOT rather than hand-maintained.
 */
export function buildAgentsMd(repoRoot: string): string {
  const rules = readRules(repoRoot);
  const skills = discoverSkillIndex(repoRoot);
  const workflows = discoverWorkflowIndex(repoRoot);

  const lines: string[] = [
    "<!-- Generated by oma emit --target agents-md. Source: .agents/ -->",
    "",
    "# AGENTS.md",
    "",
    "Portable instruction file for AI coding agents. Generated from the",
    "`.agents/` source of truth in this repository.",
    "",
    "## Skills",
    "",
    "| Skill | File | Description |",
    "|-------|------|-------------|",
  ];
  for (const skill of skills) {
    lines.push(
      `| ${skill.name} | \`${skill.file}\` | ${toTableCell(skill.description)} |`,
    );
  }

  lines.push(
    "",
    "## Workflows",
    "",
    "| Workflow | File | Description |",
    "|----------|------|-------------|",
  );
  for (const wf of workflows) {
    lines.push(
      `| ${wf.name} | \`${wf.file}\` | ${toTableCell(wf.description)} |`,
    );
  }

  if (rules.length > 0) {
    lines.push(
      "",
      "## Rules",
      "",
      "| Rule | File | Scope |",
      "|------|------|-------|",
    );
    for (const rule of rules) {
      const scope = rule.globs || (rule.alwaysApply ? "always" : "on request");
      lines.push(
        `| ${rule.name} | \`.agents/rules/${rule.name}.md\` | ${scope} |`,
      );
    }
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Emit the generated AGENTS.md to `outDir/AGENTS.md` and report whether it
 * differs from the existing root `AGENTS.md` (which is never overwritten by
 * emit — it is separately owned by `platform/rules.ts`'s vendor merge flow).
 */
export function emitAgentsMd(
  repoRoot: string,
  outDir: string,
): AgentsMdEmitReport {
  const generated = buildAgentsMd(repoRoot);

  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "AGENTS.md");
  writeFileSync(outPath, generated);

  const existingPath = join(repoRoot, EXISTING_AGENTS_MD_PATH);
  const existingExists = existsSync(existingPath);
  const existingContent = existingExists
    ? readFileSync(existingPath, "utf-8")
    : "";

  return {
    target: "agents-md",
    outPath,
    existingPath,
    existingExists,
    existingDiffers: !existingExists || existingContent !== generated,
  };
}
